version: '1'
services:
  enrich:
    image: dinhphu/snowplow-enrich:1.0.0
    container_name: enrich1
    # restart: always
    depends_on:
      - iglu-server
  iglu-server:
    image: dinhphu/snowplow-iglu:1.0.0
    container_name: iglu-server1
    # restart: always
    ports:
      - 8182:8182
    depends_on:
      - postgresdb
  postgresdb:
    image: dinhphu/iglu-postgres:1.0.0
    container_name: postgresdb
    # restart: always
    ports:
      - 5433:5433
